### ISSUE TITLE
Create a GUI for generation of .exe file

### ISSUE THREAD

**Issue by CYBERDEVILZ** [CYBERDEVILZ/Cryptonite#24]
Configuration of Cryptonite.py is sometimes a cumbersome task. A gui is required that will ask the user to enter the necessary details, which will finally create executable file for Cryptonite.py

**Comment by CYBERDEVILZ** [comment]
Basic working framework is done!
Check these commits: ![commit 1](https://github.com/CYBERDEVILZ/Cryptonite/commit/1bc7bff2522efaff66c9fda7e3c01fac5ac8a08e), ![commit 2](https://github.com/CYBERDEVILZ/Cryptonite/commit/a144aea879fb913fde79022b8151d728b0b350cb)

**Comment by P0intMaN** [comment]
looks great! but what's with all those commented codes in commit 1? Couldn't you just simply remove them?

**Comment by CYBERDEVILZ** [comment]
I did. Check the second commit
