### ISSUE TITLE
pandas module issue on command python CommandCenter.py

### ISSUE THREAD

**Issue by Toornad0** [CYBERDEVILZ/Cryptonite#49]
after giving python CommandCenter.py error is showing and not opening 127.0.0.1
![s2](https://user-images.githubusercontent.com/92824138/137994995-68166187-01cc-400a-9a21-c83f41bff64a.png)
![s3](https://user-images.githubusercontent.com/92824138/137994999-4f5c1eb2-a69a-4e04-87e0-ca8e002fd288.png)

----
![s1](https://user-images.githubusercontent.com/92824138/137995046-bca8d06c-8784-40d7-8ab6-2b6ee2befcd8.png)

How to fix this last error please help

**Comment by Toornad0** [comment]
Okay let me check

**Comment by Toornad0** [comment]
Yes

**Comment by Toornad0** [comment]
Let me check 😂

**Comment by CYBERDEVILZ** [comment]
Yes, yes please let me know if everything works smoothly

**Comment by Toornad0** [comment]
All good works perfectly it was awesome project really so much appreciated
for your guidelines and this great full learning experience just awesome
keep it up brother. Thank you can i get you raid forum username? And other
social links to follow you?

**Comment by Toornad0** [comment]
Awesome, thanks!

**Comment by CYBERDEVILZ** [comment]
The issue has been resolved in PR https://github.com/CYBERDEVILZ/Cryptonite/commit/2ec00d80ef1e11f6c67588037a4cd38d872ca983.
Thanks to @Toornad0 for bringing ups this issue.
