### ISSUE TITLE
Import "PIL" could not be resolved from source

### ISSUE THREAD

**Issue by chicabenjamin82** [CYBERDEVILZ/Cryptonite#53]
Hi I tried running the repo in sequence as you instructed. However when running exeGen.py, PIL can't be found. 

![image](https://user-images.githubusercontent.com/96936348/147846319-3c533683-07d8-435b-b34d-62a6af4e0b43.png)

What is the problem here sir?

**Comment by CYBERDEVILZ** [comment]
Most probably Pillow library is not installed. Just type "pip install Pillow" inside the terminal and you are good to go
