### ISSUE TITLE
change the ransom message

### ISSUE THREAD

**Issue by francoiga** [CYBERDEVILZ/Cryptonite#55]
Hi, first thanks for your work, is it possible to modify the ransom message to use our own words or change the language?

**Comment by CYBERDEVILZ** [comment]
Hi @francoiga
Glad you loved Cryptonite.
Coming to your question, it is absolutely possible to change the message of Cryptonite. All you have to do is edit the message present in Cryptonite.py file ("WARNING!" is present in line number 183, "Some / All of Your Files Have Been Encrypted!" is present in line number 185, etc...). Edit these texts and adjust as per your need.

**Comment by francoiga** [comment]
Thanks for your answer, I have another problem in CommandCenter.py. The message error is [{
	"resource": "/c:/Users/Administrator/Desktop/Cryptonite-main/Cryptonite/CommandCenter.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"pandas\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 9,
	"startColumn": 8,
	"endLineNumber": 9,
	"endColumn": 14
}]

I hope you have solution :)
