### ISSUE TITLE
Problem in CommandCenter.py.

### ISSUE THREAD

**Issue by francoiga** [CYBERDEVILZ/Cryptonite#56]
Thanks for your answer, I have another problem in CommandCenter.py. The message error is [{
	"resource": "/c:/Users/Administrator/Desktop/Cryptonite-main/Cryptonite/CommandCenter.py",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingModuleSource",
		"target": {
			"$mid": 1,
			"external": "https://github.com/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md#diagnostic-severity-rules",
			"path": "/microsoft/pylance-release/blob/main/DIAGNOSTIC_SEVERITY_RULES.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "diagnostic-severity-rules"
		}
	},
	"severity": 4,
	"message": "Import \"pandas\" could not be resolved from source",
	"source": "Pylance",
	"startLineNumber": 9,
	"startColumn": 8,
	"endLineNumber": 9,
	"endColumn": 14
}]

I hope you have solution :)

_Originally posted by @francoiga in https://github.com/CYBERDEVILZ/Cryptonite/issues/55#issuecomment-1100827659_

**Comment by P0intMaN** [comment]
Ah, this is a general missing module scenario. From the error message, I can see that your system might not have *`pandas`* installed. 

You can install *`pandas`* by going to your terminal ( or CMD) and type:

```bash
pip install pandas
```
This should fix the problem.

**Comment by P0intMaN** [comment]
And thanks for pointing this issue out, @francoiga! Seems like @CYBERDEVILZ hasn't added *`pandas`* in the **requirments.txt** file. 

I will patch this up rn by issuing a concerned PR.
Thanks!

**Comment by CYBERDEVILZ** [comment]
It completely evaded my mind to update the requirements file. Thanks for updating the requirements file @P0intMaN
